author:
  name: Alex Gordon
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fc1fd7d0-1eb1-4ee0-b85d-a5d955dd3922.jpg
color:
  saturation: 0.9880178067833185
  brandStrength: 1
  rhythmicContrast: 0.9710342704784125
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#C6C6C6'
    - '#939393'
    - '#6D6D6D'
  lightness: 0.771256263833493
typography_spectrum: 0.09856631
navigation:
  - id: 0fa92e0c-bec6-4a6f-8f77-6233f4190b48
    name: About Us
    type: content
  - id: 009678ee-f4aa-4329-aa8f-dbb892c9201f
    name: TOUR DATES
    type: content
  - id: 4038887d-ef57-4fbf-88fb-c67bb8ba655b
    name: Discography
    type: content
layout_spectrum: 1
name: AG OFFICIAL
